In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('./data/vectors_and_result.csv')

In [21]:
df.head(5)

vectors  result_Encoded
0  [-9.63518322e-02  7.74816573e-02 -1.16868161e-...               1
1  [-1.25304386e-01 -6.69004321e-02  4.21522558e-...               1
2  [ 3.92924733e-02  4.26425934e-02 -3.94972563e-...               1
3  [-1.34194896e-01 -3.17145765e-01 -1.05994157e-...               1
4  [-1.59152254e-01  7.72438571e-02 -2.12291814e-...               1

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
def parse_vector(vec_str):
    cleaned = vec_str.strip('[]').split()
    return np.array([float(x) for x in cleaned])


In [24]:
df['vectors'] = df['vectors'].apply(parse_vector)

In [25]:
df_sampled = (
    df.groupby("result_Encoded")
      .sample(n=4000, random_state=42)
      .reset_index(drop=True)
)

X = np.vstack(df_sampled["vectors"].values)
Y = df_sampled["result_Encoded"].values

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [27]:
X_train , Y_train , X_test , Y_test

(array([[ 0.02173055, -0.06932012,  0.15723936, ..., -0.45414639,
         -0.07147238,  0.06306854],
        [ 0.07720996, -0.04855201, -0.00449588, ..., -0.17450136,
          0.09281159,  0.03088921],
        [-0.06738908,  0.04973784,  0.18692956, ..., -0.1773451 ,
          0.15984978,  0.18017447],
        ...,
        [ 0.03535689,  0.04039188,  0.03907369, ..., -0.16911558,
          0.20653923,  0.09375005],
        [-0.061485  ,  0.03796046,  0.06613464, ..., -0.2483276 ,
         -0.00488773,  0.0575887 ],
        [-0.01477031, -0.01460087,  0.0932814 , ..., -0.07934879,
          0.06685717,  0.05747488]]),
 array([6, 2, 6, ..., 0, 3, 5], dtype=int64),
 array([[ 0.1558402 ,  0.23353258,  0.09901106, ..., -0.02214072,
          0.15780312,  0.03498715],
        [ 0.05686134,  0.02963237,  0.15336521, ..., -0.08679997,
          0.0856237 ,  0.17847852],
        [-0.01403933, -0.03485479, -0.0955468 , ..., -0.43791118,
         -0.03311872,  0.08803639],
        ...,
        

In [28]:
df_sampled['result_Encoded'].value_counts()

result_Encoded
0    4000
1    4000
2    4000
3    4000
4    4000
5    4000
6    4000
7    4000
Name: count, dtype: int64

In [29]:
from sklearn.svm import SVC

In [30]:
model = SVC(kernel="rbf",gamma='scale',C = 1, probability=True)

In [31]:
model.fit(X_train,Y_train)

SVC(C=1, probability=True)

In [32]:
import pickle    

In [33]:
with open ("./pickle_files/classification_model.pkl","wb") as f:
    pickle.dump(model,f)